### QUOTE

GET http://localhost:8888/stayAwhileAndListen/quotes/allQuotes

###
POST localhost:8888/stayAwhileAndListen/quotes/addQuote
Content-Type: application/json

{
  "name": "Samwise 321312",
  "diablo2Character": {
    "name": "Big dsadasdasdccxzcxxzc"
  }
}

###
DELETE http://localhost:8888/stayAwhileAndListen/quotes/deleteQuote/12

###
GET http://localhost:8888/stayAwhileAndListen/quotes/getQuote/Oh shit.mp3

###
PUT http://localhost:8888/stayAwhileAndListen/quotes/editQuote/13
Content-Type: application/json

{
  "name": "Testowy Samwise Gamdzej numer 6321",
  "diablo2Character": {
    "name": "Big dsadasdasdccxzcxxzc"
  }
}

### CHARACTER

GET http://localhost:8888/stayAwhileAndListen/character/allCharacters

###
POST http://localhost:8888/stayAwhileAndListen/character/addCharacter
Content-Type: application/json

{
  "name": "Izual",
  "description": "Izual was once an angel in service to the High Heavens[1], and served as the most trusted lieutenant of Tyrael during the Great Conflict."
}

###
GET http://localhost:8888/stayAwhileAndListen/character/getCharacter/Akara

###
PUT http://localhost:8888/stayAwhileAndListen/character/editCharacter/21
Content-Type: application/json

{
  "name": "Izual",
  "description": "Izual was once an angel in service to the High Heavens, and served as the most trusted lieutenant of Tyrael during the Great Conflict."
}

###
DELETE http://localhost:8888/stayAwhileAndListen/character/deleteCharacter/20
